-- dim_movie definition

create table dim_movie(
dw_movie_id int not null,
imdb_title_id varchar(100) not null,
title varchar(255) not null,
original_title varchar(255) not null,
year int,
date_published timestamp not null,
genre varchar(255),
duration int,
country varchar(255),
language varchar(100),
director varchar(255),
writer varchar(255),
production_company varchar(255),
actors varchar(1000),
description varchar(1000),
budget varchar(255),
dw_created_dt datetime not null default current_timestamp,
dw_modified_dt datetime not null default current_timestamp,
dw_created_by varchar(50) not null default 'etl',
dw_modified_by varchar(50) not null default 'etl',
dw_load_id int not null default 1);


-- dim_person definition

create table dim_person(
dw_person_id int not null,
imdb_name_id varchar(100) not null,
name varchar(255) not null,
birth_name varchar(255),
height int,
bio varchar(5000),
birth_details varchar(1000),
birth_year int,
date_of_birth timestamp not null,
place_of_birth varchar(1000),
death_details varchar(1000),
death_year int,
date_of_death timestamp,
place_of_death varchar(1000),
reason_of_death varchar(1000),
spouses int,
divorces int,
spouses_with_children int,
children int,
primary_profession varchar(1000),
dw_flag boolean not null,
dw_created_dt datetime not null default current_timestamp,
dw_modified_dt datetime not null default current_timestamp,
dw_created_by varchar(50) not null default 'etl',
dw_modified_by varchar(50) not null default 'etl',
dw_load_id int not null default 1);

-- fact_movie_rating definition

create table fact_movie_rating(
dw_fact_id int not null,
dw_movie_id int not null,
weighted_average_vote float not null,
total_votes int,
mean_vote float,
median_vote float,
votes_10 int,
votes_9 int,
votes_8 int,
votes_7 int,
votes_6 int,
votes_5 int,
votes_4 int,
votes_3 int,
votes_2 int,
votes_1 int,
allgenders_0age_avg_vote int,
allgenders_0age_votes int,
allgenders_18age_avg_vote float,
allgenders_18age_votes int,
allgenders_30age_avg_vote float,
allgenders_30age_votes int,
allgenders_45age_avg_vote float,
allgenders_45age_votes int,
males_allages_avg_vote float,
males_allages_votes int,
males_0age_avg_vote float,
males_0age_votes int,
males_18age_avg_vote float,
males_18age_votes int,
males_30age_avg_vote float,
males_30age_votes int,
males_45age_avg_vote float,
males_45age_votes int,
females_allages_avg_vote float,
females_allages_votes int,
females_0age_avg_vote float,
females_0age_votes int,
females_18age_avg_vote float,
females_18age_votes int,
females_30age_avg_vote float,
females_30age_votes int,
females_45age_avg_vote float,
females_45age_votes int,
top1000_voters_rating float,
top1000_voters_votes int,
us_voters_rating float,
us_voters_votes int,
non_us_voters_rating float,
non_us_voters_votes int
avg_vote float,
votes int,
budget varchar(255),
usa_gross_income float,
worlwide_gross_income float,
metascore int,
reviews_from_users int,
reviews_from_critics int,
dw_created_dt datetime not null default current_timestamp,
dw_modified_dt datetime not null default current_timestamp,
dw_created_by varchar(50) not null default 'etl',
dw_modified_by varchar(50) not null default 'etl',
dw_load_id int not null default 1);


-- bridge_movie_person definition

create table bridge_movie_person(
bridge_id int,
dw_movie_id int,
dw_person_id int,
imdb_title_id varchar(100) not null,
imdb_name_id varchar(100) not null,
category varchar(100),
job varchar(100),
characters varchar(255));
